apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        collection_interval: 1m
        scrapers:
          cpu:
          load:
          memory:
          disk:
          filesystem:
          network:
          paging:
          processes:     

      kubeletstats:
        collection_interval: 10s
        auth_type: 'serviceAccount'
        endpoint: '${env:K8S_NODE_NAME}:10250'
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container

      k8s_cluster:
        collection_interval: 10s
        auth_type: 'serviceAccount'

    processors:
      batch:
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s

      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 500

      k8sattributes:
        auth_type: 'serviceAccount'
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.uid

    exporters:
      debug:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: "http://prometheus:9090/api/v1/write"

      prometheus:
        endpoint: "0.0.0.0:8889"
        enable_open_metrics: true

      otlp/tempo:
        endpoint: "http://tempo:4317"
        tls:
          insecure: true

      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

    service:
      pipelines:
        metrics:
          receivers: [otlp, kubeletstats, k8s_cluster, hostmetrics]
          processors: [batch]
          exporters: [prometheusremotewrite, debug]

        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter, k8sattributes]
          exporters: [otlp/tempo]

        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter, k8sattributes]
          exporters: [loki]
